### ISSUE TITLE
p240 5.2.10 테스트 환경구축

### ISSUE THREAD

**Issue by 0r0loo** [wikibook/ts-nextbook-app#3]
~~jest-environ-ment-jsdom // jest-environment-jsdom~~

줄바뀜은 -로 표시

**Comment by wikibook** [comment]
@0r0loo 님, 안녕하세요.
위키북스 담당자입니다.

이슈에 올려주신 내용을 확인했는데, 240쪽 내용은 말씀하신 대로 다음과 같이 수정해야 맞습니다.

~~~
$ npm install --save-dev @testing-library/jest-dom @testing-library/react jest jest-environment-jsdom
~~~

해당 내용을 정오표에 등록했습니다. 불편을 드려서 죄송하고, 오류를 바로잡을 수 있게 알려주셔서 감사합니다. 수정된 내용은 다음 번에 인쇄할 때 반영하도록 하겠습니다.

https://wikibook.co.kr/ts-react-nextjs/

그럼 오늘도 좋은 하루 보내세요!
고맙습니다.
